spring:
  application:
    name: middle
  profiles:
    active: eureka,security,default
server:
  session:
    timeout: 5000
  port: 8011
feign:
  oauth2:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
    